dockerfile: |-
  RUN apk add --no-cache build-base git

script: &script |-
  echo -e "\e[1m"
  ruby -v
  echo -e "\e[0m"
  gem install bundler
  bundle install --full-index
  bundle exec rake spec

fail_fast: true

images:
  ruby:3.3-alpine: *script
  ruby:3.2-alpine: *script
  ruby:3.1-alpine: *script
  ruby:3.0-alpine: *script
