dockerfile: |-
  RUN apk add --no-cache build-base yaml-dev openssl-dev git

script: &script |-
  echo -e "\e[1m"
  ruby -v
  echo -e "\e[0m"
  bundle install --jobs=$(getconf _NPROCESSORS_ONLN)
  bundle exec rake spec

fail_fast: true

before: |-
  rm -vf Gemfile.lock

after: |-
  rm -vf Gemfile.lock

images:
  ruby:4.0-alpine: *script
  ruby:3.4-alpine: *script
  ruby:3.3-alpine: *script
  ruby:3.2-alpine: *script
  ruby:3.1-alpine: *script
